#ifndef GAMEPLAYBACKGROUND_BITMAP_H
#define GAMEPLAYBACKGROUND_BITMAP_H
extern const unsigned short gameplayBackground[38400];
#define GAMEPLAYBACKGROUND_WIDTH 240
#define GAMEPLAYBACKGROUND_HEIGHT 160
#endif