#ifndef GAMEOVERBACKGROUND_BITMAP_H
#define GAMEOVERBACKGROUND_BITMAP_H
extern const unsigned short gameOverBackground[38400];
#define GAMEOVERBACKGROUND_WIDTH 240
#define GAMEOVERBACKGROUND_HEIGHT 160
#endif